Update django.yml

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -28,3 +28,10 @@ jobs:
     - name: Run Tests
       run: |
         python 07-practicing-urls-and-views/manage.py test
+    - name: Run Django server with Gunicorn
+      run: |
+        python 07-practicing-urls-and-views/manage.py migrate
+        nohup gunicorn 07-practicing-urls-and-views.wsgi:application --bind 127.0.0.1:8000 &
+        sleep 5
+        curl --fail http://127.0.0.1:8000 || (echo "Server failed to respond" && exit 1)
+
